name: 'deploy-nodejs-reporters'

on:
  push:
    branches:
      - "cross-os-test"
    paths:
      - '**.js'
      - '**.ts'
      - '**test-windows.yml' # for testing this workflow

permissions:
    contents: write

jobs:
    cross-version-test-for-mac:
      runs-on: ${{ matrix.os }}

      strategy:
        matrix:
          os: [ 'macos-latest', 'macos-12', 'macos-11']

      name: cross-version-test-for-mac
      permissions: write-all

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Use Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20.9.0

        - name: Setup Turbo Repo.
          working-directory: ./handshake-nodejs-reporters
          run: sudo npm install && npm run build

        - name: conduct sanity tests
          working-directory: ./handshake-nodejs-reporters
          run: sudo npm run sanity

        - name: generate test reports
          working-directory: ./handshake-nodejs-reporters
          run: sudo npm run export-sanity-results

        - name: verify test reports
          working-directory: ./handshake-nodejs-reporters
          run: sudo npm run verify-sanity
